security:
    # Encoders ou Password Hashers
    password_hashers:
        App\Entity\User:
            algorithm: auto

    providers:
        # On définit comment on récupère les utilisateurs depuis la base
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        # Le "firewall" principal
        main:
            pattern: ^/
            provider: app_user_provider
            stateless: true
            json_login:
                check_path: /api/login
                username_path: email
                password_path: password
            # On dit à Symfony d'utiliser lexik_jwt pour l'authentification
            jwt: ~

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)
            security: false

    access_control:
        # Exige d'être connecté pour toute route commençant par /api sauf /api/login
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
