controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# api/config/routes.yaml
auth:
    path: /api/auth
    methods: ['POST']

test_send_mail:
    path: /password/reset
    controller: App\Controller\PasswordResetController::sendMail
    methods: ['POST']

# config/routes.yaml
app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }