controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# api/config/routes.yaml
auth:
    path: /api/auth
    methods: ['POST']

forgot-password:
    path: /forgot-password
    controller: App\Controller\ForgotPasswordController::sendMail
    methods: ['POST']

reset-password:
    path: /reset-password
    controller: App\Controller\ResetPasswordController::controlToken
    methods: ['GET']

change-password:
    path: /change-password
    controller: App\Controller\ResetPasswordController::changePassword
    methods: ['PUT']

# config/routes.yaml
app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }